#ifndef PIN_FUNC
#define PIN_FUNC
#include "fpioa.h"
//硬件引脚定义
//KEYPAD
#define PIN_KEYPAD_L (1)
#define PIN_KEYPAD_M (2)
#define PIN_KEYPAD_R (3)
//LED
#define PIN_RED_LED (0)
#define PIN_GREEN_LED (17)
//软件索引编号定义
//KEYPAD
#define KEYPAD_L_GPIOHSNUM (0)
#define KEYPAD_M_GPIOHSNUM (1)
#define KEYPAD_R_GPIOHSNUM (2)
//LED
#define RED_LED_GPIONUM (0)
#define GREEN_LED_GPIONUM (1)
//软件功能定义
//KEYPAD
#define FUNC_GPIOHS_KEYPADL (FUNC_GPIOHS0 + KEYPAD_L_GPIOHSNUM)
#define FUNC_GPIOHS_KEYPADM (FUNC_GPIOHS0 + KEYPAD_M_GPIOHSNUM)
#define FUNC_GPIOHS_KEYPADR (FUNC_GPIOHS0 + KEYPAD_R_GPIOHSNUM)
//LED
#define FUNC_GPIO_LEDR (FUNC_GPIO0 + RED_LED_GPIONUM)
#define FUNC_GPIO_LEDG (FUNC_GPIO0 + GREEN_LED_GPIONUM)

#endif